stages:
  - lint
  - test

before_script:
  - pip install -r dev-requirements.txt

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

lint:
  stage: lint
  image: python:3.6
  script:
    - make lint
  
test_py27:
  stage: test
  image: python:2.7
  script:
    - tox -e 'py27'

test_py34:
  stage: test
  image: python:3.4
  script:
    - tox -e 'py34'

test_py35:
  stage: test
  image: python:3.5
  script:
    - tox -e 'py35'

test_py36:
  stage: test
  image: python:3.6
  script:
    - tox -e 'py36' 
