notifications:
  email:
    on_success: never
    on_failure: change
sudo: false
language: python
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: f4hQQE4qMRQOuJwsjO4gm+OtJ5FlmbAZRh8377+5W4kjqzPyY30fPdV3wUnhhIQGdGiHkhfv0DiJ/abb0DKYmPG84H4ADLNyQ0qArAMtsHLucEB88kFHlYDLeKHM4jIM6PpoSzqg+ifojwspY4HbyUHnBZZdmhmrPCH+rsPCKEdu3bQFWJO6GfTLiE+gu2fu8GwyBgdhpebhqSO0O2i1wzanIEGBjkuaq5oVZ44GGKxC6Nk/Pa/JTKGNipVMHSxLOAqV3bsRLBR+LBi/MCdHISpCH8lZs9NOaL9u5sLNY3ueY4DzRdIODr5kicZkOjKD17IRjlQrKpvz6rTm3UNa7+hdWXb9ElVo8ViTx2vjloxxA4NW34WPpcYz3FxFUQ/M3tiTAPl/8R+jdbEO2kTTNjsVdtV1zWP+VbnhuSnKXVDp0wJ1fKhCjgUs1KkwxZ9yAaQF1s9yUePA815b62BgStzui/MyXVifT1dy5tYzQLhD5Q0bPTyBwEJaz7vwImAPh6LVRxQhAQJmKuhKcq6GqBS4KSXEXWbUAIaFJ0PYmhZPMetCcYrEmoqiPiGsu3tlpLDvZx/2+PsZ/LK54xgjzAoG2z6PBowpXsk6+KjJgRF32KjYl+vv0olU4aAehQRsYQGCSuciQ7PCaKwIcLItGdajk1zu8wtiqSa+7hKud4c=
before_install:
- if [ -z "$GITHUB_ACCESS_TOKEN" ]; then echo "Environment requires access token"
  && exit 1; fi
install:
- pip install -r dev-requirements.txt
after_success:
- tox -e coverage-report
jobs:
  include:
  - stage: lint
    python: '3.6'
    script: make lint
  - stage: test
    python: '3.6'
    env: TOXENV=py36
    script: make test
  - stage: release
    if: branch = master AND tag IS blank
    python: 3.6
    before_install: skip
    after_success: skip
    script:
    - "./travis-pypi-release.sh"
    env:
    - secure: qRbj71375w7jHenCOdxvF2mEbLH6KYD+QBmVXZnaRB4R3WdS1ghThYwzTBmalBVFqQ2E3LOTY4TIvhCxPIhPaTyRi2kHXKGke6NR4z/rlbMLYm9VRBLG+4dT9LuRYW0xH1XPmo54OCLdS1zPASV5pXoanMwFqKgerfoUjX8WWM/yNz37j4VflBVVQ9lKGsfwbDyK7XpN3kOO4oiC9tFTnzGc6zS7vxfHkqCEB/otPKBdkFED8ZwmaJ0D20MOE619YTMtf0mwxL+PyIEtIO+ocpmfLJILseEicoFrDOgcoJZv2ZS30nsu2MQHZZxvMmI0NNn7fMjMVqdQ5fCPm9V/ASg/b6fqdllDBuSHNyb1sX6ZzVBYPY8RsnjOxZNQzw++ZTOqFW9LF5rADjcUvCcS44Ue8rCL3q7Ob7Xw5fXW0EDqLioTooCsPK00qrPl1s9/bMrhXqRWGv23qcexzwAt7MsqiORhi82Kj3ks9Zn9y4e4qNxtgikQaULXVAUcAsnBRwEm+XHdBWo8FpPi1GFeX+cc73k9+e0lGCMS6LnQsYDaRPPwkfjfXi3IA26obxE6hoPtyQ39PWB0YFVTg9vQmZFA1uFwQXoF2JPIw//Iy50BF9SvJ6xJwWJ4AHeYnDK2rOcGK0cxWSzyl/zmWrb91uBOMnXioxhLA0clWcP+QmI=
    - secure: NirIw8sU1aLM2ESLtDfApQRnFSDvA0YSi1Fpgnh+wnv5SLZQRljKfFHr03O5nky6MrKl9XesDbsOWXK9GM63iAGGDZUuUdmcHlNqi/+aYSiM99yhzxLUPPLpsBgU0iigcsNsX00NFzrNOV+PETwyGqhgdjnwOz0KHKugk8TOokl1yxnmTMRVzuKin/DR+0Y7zILcybl5GLb+Gtk5WGJD6lJ8+trxW7zWH25HAHLMh11vXuP0nrjJ0le0CYKh68/O8M5fZe+H5kyhtt6MIASjxZyJnfEq8GG4KUQMLrj2KViJOG3fHm52w1jYeCDmCSbmaL3bm2ZY+oDRS4eA1RtKUxsMS9o13sRaRa+vhT1Y4rwzOMEGMQw4ykIp5uXm4Fnc4YQPn+AY+zswnL1BMaIdj4ekXBgE9GSzxMumDE8gIVTq9YrcodF/dz9hLXj21T0UQ08mnOasvU35n4HKGB4XkHjPUF+6lDb7m/xmxXX7RCGt2YCcJS2h3AsFPmMdjR5tk4IdWzc1v1pf9cFVovFy82+MCMbWwvuF11Gw6pFN+OZR1XssY0nd+3IZgE8BzrNu5wyuHTrDlAjqI0a6tr8FbK8q/hHQacCc2Zs6lm63GGUBWsGH8RF8y+rzOpv4PtI9jMtqXBeuKq+OTYeWoxWNIqFCgpA/2moQAstJwksYQAU=
    - secure: GAvPFIoNX7x6tYIX2C0dmlUBeleMHbkmk3wt5PFK0UCZHoT3X2YUFfUDyt++Lcjf9PmezbCI6xptsm817XNGE2A/L/xkYS11fQwC9GqUr8PgD9o+UX+mvPnMCwlGXYDtrHzR/qnQgKo1pPXQYRXEBRIKsCjwRrg4748vQSkqrgaxAhJzaugco4YcbBKhyxxMMJlhMqwJsh0HWJ7/Yg/g2p8XYRX6Rz5xNcjrO5iDqadEQzmq9kSH+n0wP6N0N0qqn8a5JBvbTHrySoE6Rh+cCmLKAIZYJsfKV1Jr7Qt8hPYYa5AtV9J304FyemgB0e7qh0DgGu0xwBmCgGBVqrg2IggSCmOsxJYG2ijemR7fzjtsIbKAn9pcFWf/q2U8osBkN5mEE81k0YfbQUnxpsdaYtanispvpOJ9GVlLeoqTDSIErsEEYT0WLgiK7J/mfqMI5r/RjtYhfIAUhozUV44uWqHngnVhVujm3G4fw+ok7otbejRzEoetYVj+Nv4p5LzjuddZAEVBaTxJZSQfjJSJkaWItZefmFjlNFQKybUIs8clg2H+EGFs9hKu3ET9m4+oLi5+1zs+fnWGD+8W8qqNL8UUNv3lBFFQEFlCbcJ36FmIgOUWXy94Gjr0cl49Q2jlELKyZTHC8cbzrTc4zFAMp7LAWH8AUk5pZXPpjZCabj8=
