sudo: false
language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install -r dev-requirements.txt

before_script:
  - make lint

script:
  - tox

after_success:
  - tox -e coverage-report
